Repository scylladb/scylla-operator-images, pull requests merged in 2023-10, with the labels that each got.

#29 Remove old and unused images
  Makefile
  base/ubuntu/20.04/Dockerfile
  golang/1.18/download-file.sh
  golang/1.19/download-file.sh
Labels: priority/important-soon, lgtm, size/M, kind/cleanup

#28 Make sure there is no old data on curl retries
  golang/1.20/download-file.sh
Labels: size/XS, priority/important-soon, lgtm, kind/bug

#31 Remove old image leftovers
  golang/1.18/Dockerfile
  golang/1.19/Dockerfile
Labels: priority/important-soon, lgtm, size/M, kind/cleanup, do-not-merge/contains-merge-commits

#27 Migrate to new CI and muti arch
  .github/workflows/go.yaml
  Makefile
  OWNERS
  golang/1.20/Dockerfile
  hack/build-images.sh
  image-spec.csv
  kube-tools/latest/Dockerfile
  kube-tools/latest/download-file.sh
Labels: lgtm, approved, size/L

#32 Upgrade base image OS
  base/ubuntu/22.04/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/feature, approved

#33 Add Go 1.21 image
  golang/1.21/Dockerfile
  golang/1.21/download-file.sh
  image-spec.csv
Labels: priority/important-soon, lgtm, size/M, kind/feature, approved

#34 Add poetry image for building the docs
  image-spec.csv
  poetry/1.5/Dockerfile
Labels: priority/important-soon, lgtm, size/S, kind/feature, approved

#35 Fix poetry location and add sanity check
  poetry/1.5/Dockerfile
Labels: size/XS, lgtm, kind/bug, priority/critical-urgent, approved

#36 Add git to poetry for sphinx multiversion builds
  poetry/1.5/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/feature, approved
