Repository scylladb/scylla-operator-images, pull requests merged in 2024-10, with the labels that each got.

#70 Update python version to 3.12 in poetry 1.8 image
  poetry/1.8/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/feature, approved

#71 Downgrade python version to 3.11 in poetry 1.8 image
  poetry/1.8/Dockerfile
Labels: size/XS, lgtm, kind/bug, priority/critical-urgent, approved

#67 Add tar to UBI base image so it works with kubectl cp
  base/ubi/9.4-minimal/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/bug, approved

#72 Stop building poetry-1.5
  image-spec.csv
  poetry/1.5/Dockerfile
Labels: priority/important-longterm, lgtm, size/S, kind/cleanup, approved

#73 Add findutils needed by node tuning
  base/ubi/9.4-minimal/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/feature, approved

#75 Add mount command needed by scylla-operator node tuning
  base/ubi/9.4-minimal/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/feature, approved

#74 Automate Golang updates and bump patch versions
  golang/1.22/go1.22.8.linux-amd64.tar.gz.sum
  golang/1.22/go1.22.8.linux-arm64.tar.gz.sum
  golang/1.22/lib.sh
  golang/1.22/version.sh
  golang/1.23/Dockerfile
  golang/1.23/download-file.sh
  golang/1.23/go1.23.2.linux-amd64.tar.gz.sum
  golang/1.23/go1.23.2.linux-arm64.tar.gz.sum
  golang/1.23/lib.sh
  golang/1.23/version.sh
  golang/README.md
  golang/lib.sh
  golang/update.sh
Labels: priority/important-soon, lgtm, kind/feature, approved, size/L

#76 Add netcat to node-setup helper image
  node-setup/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/feature, approved
