Repository scylladb/scylla-operator-images, pull requests merged in 2024-09, with the labels that each got.

#54 Add basic set of base ubi9.4-minimal
  base/ubi/9.4-minimal/Dockerfile
  base/ubi/9.4-minimal/almalinux.repo
  base/ubuntu/22.04/Dockerfile
  golang/1.21/Dockerfile
  golang/1.22/Dockerfile
  image-spec.csv
  node-setup/Dockerfile
Labels: priority/important-longterm, lgtm, size/M, kind/feature, approved

#58 installing missing dependencies for go test
  base/ubi/9.4-minimal/Dockerfile
  base/ubi/9.4-minimal/almalinux-appstream.repo
  golang/1.21/Dockerfile
  golang/1.22/Dockerfile
Labels: lgtm, kind/bug, size/S, priority/critical-urgent, approved

#56 Update golang versions
  golang/1.22/Dockerfile
  golang/1.23/Dockerfile
  golang/1.23/download-file.sh
  image-spec.csv
Labels: priority/important-soon, lgtm, size/S, kind/feature, approved

#59 Update buildah to 1.37
  buildah/latest/Dockerfile
Labels: size/XS, priority/important-soon, lgtm, kind/feature, approved

#63 Update kube-tools image
  kube-tools/latest/Dockerfile
Labels: priority/important-soon, lgtm, size/S, kind/feature, approved
