Repository scylladb/scylla-operator-images, pull requests merged in 2025-01, with the labels that each got.

#82 Remove tnozicka from OWNERS
  OWNERS
Labels: size/XS, priority/important-soon, lgtm, kind/cleanup, approved

#83 Add `mflendrich` to `OWNERS`
  OWNERS
Labels: size/XS, priority/important-soon, lgtm, kind/cleanup, approved

#85 Stop building Go 1.22
  golang/1.22/Dockerfile
  golang/1.22/download-file.sh
  golang/1.22/go1.22.9.linux-amd64.tar.gz.sum
  golang/1.22/go1.22.9.linux-arm64.tar.gz.sum
  golang/1.22/lib.sh
  golang/1.22/version.sh
  image-spec.csv
Labels: priority/important-soon, lgtm, size/M, kind/cleanup, approved

#84 Update Go to 1.23.5
  golang/1.23/go1.23.3.linux-amd64.tar.gz.sum
  golang/1.23/go1.23.3.linux-arm64.tar.gz.sum
  golang/1.23/go1.23.5.linux-amd64.tar.gz.sum
  golang/1.23/go1.23.5.linux-arm64.tar.gz.sum
  golang/1.23/version.sh
  kube-tools/latest/Dockerfile
Labels: priority/important-soon, lgtm, size/S, kind/feature, approved

#86 Add rzetelskik to approvers
  OWNERS
Labels: size/XS, priority/important-longterm, lgtm, kind/cleanup, approved
